apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo
  namespace: swd4ta020

spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  todo
                port:
                  number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: todo
  namespace: swd4ta020
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app:  todo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  namespace: swd4ta020
  labels:
    app: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: jkavan/spring-todo:1.0.0
        ports:
        - containerPort: 8080

