apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-ci
  namespace: swd4ta020
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-role
rules:
  - apiGroups:
      - ""
      - apps
      - networking.k8s.io
    resources:
      - deployments
      - ingresses
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-role-cluster-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deployment-role
subjects:
  - kind: ServiceAccount
    name: github-ci
    namespace: swd4ta020
---
apiVersion: v1
kind: Secret
metadata:
  name: github-ci-token
  namespace: swd4ta020
  annotations:
    kubernetes.io/service-account.name: github-ci
type: kubernetes.io/service-account-token
